### ISSUE TITLE
get_submission.cwl makes assumptions about output from challengeutils downloadsubmission

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/ChallengeWorkflowTemplates#43]
This line: https://github.com/Sage-Bionetworks/ChallengeWorkflowTemplates/blob/master/get_submission.cwl#L34

The workflow assumes that this is exactly where the file will be written and how it will be named. But `challengeutils downloadsubmission` already provides this information as part of its output.

I think this fix is as simple as replacing that line with something like:
```
$(JSON.parse(self[0].contents)['file_path'])
```

**Comment by thomasyu888** [comment]
@philerooski, Thanks for reporting.  Did you get an error when running your workflow?  This is because `challengeutils` itself renames the submission file when `output` is defined as a parameter.  That being said, I do print the json in stdout.

https://github.com/Sage-Bionetworks/challengeutils/blob/master/challengeutils/__main__.py#L86

But what you're suggesting is:

```
  - id: filepath
    type: File?
    outputBinding:
      glob: results.json
      loadContents: true
      outputEval: $(JSON.parse(self[0].contents)['file_path'])
```
